### ISSUE TITLE
Come up with a plugin system

### ISSUE THREAD

**Issue by DanilAndreev** [Pathfinder-Systems/pathfinder-slave#1]
Come up with a __plugin__ system. Create __dependencies diagram__.
### Requirements
* Flexible system for all programs
* Python based plugins
* Security restrictions for plugins

**Comment by JeyM1** [comment]
https://drive.google.com/file/d/1_HvKhzFaJ5gZYrnZl4ZjP_MpXyCoSTEe/view?usp=sharing
